### ISSUE TITLE
syntax doc

### ISSUE THREAD

**Issue by nelsonlarocca** [impankratov/redisearch-node#2]
Hi !

Any clue about the right way to declare and use it ?
Thanks !

**Comment by impankratov** [comment]
@nelsonlarocca 
Hi,
And yes, I should add some examples in readme.
Until then, you can look up syntax in test file : https://github.com/impankratov/ioredisearch/blob/07cbc3882494e0a58b810b6ce13b929c694ee495/test/ioredisearch.test.ts#L19

First parameter is the index name, second is an instance of ioredis client. That's it!
